name: Lint, Build, Test
on: push

jobs:
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Setup dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn run lint:ts
      - name: Prettier
        run: yarn run prettier
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Setup dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn run build
  Test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Setup dependencies
        run: yarn --frozen-lockfile
      - name: Test
        run: yarn run test
  publish:
    name: Publish
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Setup dependencies
        run: yarn --frozen-lockfile
      - name: Prepare
        run: npm run prepublishOnly
      - name: Publish
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
