name: Lint, Build, Test
on: push

jobs:
  Percy:
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Setup dependencies
        run: npm i
      - name: Build
        run: npm run build:example
      - name: Snapshot
        run: npx percy snapshot ./dist
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Setup dependencies
        run: npm i -g eslint prettier && npm i
      - name: Lint
        run: npm run lint:ts
      - name: Prettier
        run: npm run prettier
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Setup dependencies
        run: npm i
      - name: Build
        run: npm run build
  Test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Setup dependencies
        run: npm i
      - name: Test
        run: npm run test
  publish:
    name: Publish
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Setup dependencies
        run: npm i --omit=peer
      - name: Build
        run: npm run build
      - name: TEMP - force global and scoped styles
        run: |
          awk '{gsub("productionPrefix = \"jss\",","productionPrefix = \"style\",")}1' dist/index.es.js > tmp && mv -f tmp dist/index.es.js
          awk '{gsub("disableGlobal = false,","disableGlobal = true,")}1' dist/index.es.js > tmp && mv -f tmp dist/index.es.js
      - name: Publish
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
